name: Python tests

on:
  pull_request:
    branches: ["main"]
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install setuptools pytest
          python3 setup.py install
      - name: Test with pytest
        run: |
          pytest -v -s
